DELETE FROM ads;

INSERT INTO ads (title, genre, role, location, description, user_id)
VALUES ('Looking for a guitarist!!', 'metal', 'Musician', 'Montreal', 'A super cool band in Montreal is looking for a guitarist. It will be really nice if you have 5 years of experiences but not required. Feel free to reach us!', 2),
('Need A Sound Engineer ASAP!', 'Jazz', 'Sound Engineer', 'Toronto', 'Hi, We are a jazz duo. We need a sound engineer asap to setup our new studio. We are based in downtown Toronto. Convenient location accessible by TTC. Please help us.', 1),
('Female Jazz Singer Wanted', 'jazz', 'Musician', 'Winnipeg', 'Ages 19-35, Seeking a talented female vocalist with excellent range, pitch, a sense of phrasing, and an understanding of harmony. Please contact before in-person interviews. Thanks.', 6),
('guitarist looking for people to jam with', 'rock', 'Musician', 'Halifax', 'Hi, a 39 years old guitarist is looking for anyone who wants to create music and have fun! I want to learn playing with others. I love Bob Dylan, Jimi Hendrix.', 3),
('Seeking drummer/bassist', 'rock', 'Musician', 'Vancouver', 'I am looking for individuals who have talents that will contribute to a "music production". I have a carrier but my passion is for music and I would like to put together resources for an energetic band. Currently I need a drummer and bassist.', 9),
('Producer wanted :-)', 'pop', 'Producer', 'Toronto', 'looking for a creative and business partnership with a talented instrumentalist who can produce and arrange original song material for a unique pop licensing project. I am looking to develop and package a number of original song properties around a "branded" vocal performer. If you are interested, please contact us!', 7),
('Looking for an experienced pianist to bring your special event to life?', 'pop', 'Musician', 'Montreal', 'Hi, my name is Eric. I specialize in playing for special events, with a wide range of repertoire including classical, easy listening, jazz standards, and contemporary/pop music. I have extensive experience playing in weddings, bridal and baby showers, receptions, Confirmations, birthday parties, and wine and cheese events, among others. I am also a composer and producer, and can provide piano parts or orchestral elements for your music if needed, in any style. Please reach out for more details!', 10);
