DROP TABLE IF EXISTS ads CASCADE;

CREATE TABLE ads (
  id SERIAL PRIMARY KEY NOT NULL,
  title VARCHAR(255) NOT NULL,
  genre VARCHAR(255) NOT NULL,
  role VARCHAR(255) NOT NULL,
  location VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  positions_available INTEGER NOT NULL,
  created_at TIMESTAMP DEFAULT now(),
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
)